"""
Defines the discovery strategies used to find scholarship candidates.

Groups hundreds of Google Dork queries targeting government domains, universities,
CSR programs, and specific demographics to surface authentic scholarship listings.
"""

from dataclasses import dataclass
from typing import List


@dataclass
class DiscoveryStrategy:
    name: str
    queries: List[str]
    source_types: List[str]


DISCOVERY_STRATEGIES = [
    DiscoveryStrategy(
        name="government_scholarships",
        queries=[
            # ============================================================
            # GOVERNMENT / NATIONAL (Original)
            # ============================================================
            "site:gov.in scholarship 2026 apply online students",
            "site:gov.in scholarship 2026 last date apply",
            "site:gov.in scholarship 2026 undergraduate students",
            "site:gov.in scholarship 2026 college students",
            "site:gov.in scholarship 2026 university students",
            "site:gov.in scholarship 2026 BTech students",
            "site:gov.in scholarship 2026 engineering students",
            "site:gov.in scholarship 2026 merit scholarship",
            "site:gov.in scholarship 2026 financial assistance students",
            "site:gov.in scholarship 2026 higher education",
            "site:gov.in scholarship 2026 technical education",
            "site:gov.in scholarship 2026 professional courses",
            "site:gov.in scholarship 2026 undergraduate engineering",
            "site:gov.in scholarship 2026 postgraduate students",
            
            # Central Government portals
            "site:education.gov.in scholarship 2026 students",
            "site:education.gov.in scholarship scheme 2026",
            "site:education.gov.in higher education scholarship 2026",
            "site:myscheme.gov.in scholarship 2026",
            "site:myscheme.gov.in scholarships students 2026",
            "site:myscheme.gov.in education scholarship 2026",
            "site:india.gov.in scholarship 2026 students",
            "site:india.gov.in scholarship schemes 2026",
            "site:india.gov.in education scholarship 2026",

            # Ministry Specific
            "site:tribal.nic.in scholarship 2026 students",
            "site:tribal.nic.in scholarship scheme 2026",
            "site:socialjustice.gov.in scholarship 2026 students",
            "site:socialjustice.gov.in scholarship scheme 2026",
            "site:depwd.gov.in scholarship 2026 students",
            "site:depwd.gov.in scholarship scheme 2026",
            "site:minorityaffairs.gov.in scholarship 2026",
            "site:minorityaffairs.gov.in scholarship schemes 2026",
            "site:labour.gov.in scholarship 2026 students",
            "site:labour.gov.in education scholarship 2026",
            "site:railway.gov.in scholarship 2026 students",
            "site:indianrailways.gov.in scholarship 2026 students",

            # ============================================================
            # ADDITIONAL GOVERNMENT/NATIONAL QUERIES (1-30)
            # ============================================================
            "site:dst.gov.in scholarship 2026 science students",
            "site:dst.gov.in inspire fellowship 2026 application",
            "site:dbtindia.gov.in biotechnology scholarship 2026",
            "site:dusi.gov.in scholarship 2026 post matric",
            "site:desw.gov.in pmss scholarship 2026 ex-servicemen",
            "site:coirboard.gov.in scholarship 2026 artisans children",
            "site:textiles.gov.in scholarship 2026 weavers children",
            "site:coal.nic.in scholarship scheme 2026",
            "site:mines.gov.in scholarship 2026 college students",
            "site:dae.gov.in fellowship 2026 nuclear science",
            "site:isro.gov.in space science scholarship 2026",
            "site:drdo.res.in research fellowship 2026",
            "site:moef.gov.in fellowship 2026 environmental science",
            "site:moc.gov.in post matric scholarship 2026",
            "site:mhrd.gov.in csss scholarship merit list 2026",
            "site:esic.nic.in scholarship 2026 wards of insured persons",
            "site:cbse.nic.in merit scholarship single girl child 2026",
            "site:cbse.nic.in csss scholarship 2026 online apply",
            "site:sebi.gov.in research fellowship 2026",
            "site:niti.gov.in internship fellowship 2026",
            "site:necouncil.gov.in scholarship 2026 north east students",
            "site:mdoner.gov.in scholarship 2026 NER students",
            "site:culture.gov.in fellowship scholarship 2026 artists",
            "site:tourism.gov.in hospitality scholarship 2026",
            "site:sportsauthorityofindia.nic.in sports scholarship 2026",
            "site:ayush.gov.in scholarship 2026 medical students",
            "site:csir.res.in jrf srf fellowship application 2026",
            "site:icmr.nic.in research fellowship medical 2026",
            "site:icar.org.in merit scholarship agriculture 2026",
            "site:ncs.gov.in student scholarship alerts 2026",
        ],
        source_types=["GOVERNMENT"],
    ),

    DiscoveryStrategy(
        name="state_scholarships",
        queries=[
            # ============================================================
            # STATE GOVERNMENTS (Original)
            # ============================================================
            "site:gov.in scholarship 2026 Uttar Pradesh students",
            "site:gov.in scholarship 2026 Delhi students",
            "site:gov.in scholarship 2026 Haryana students",
            "site:gov.in scholarship 2026 Punjab students",
            "site:gov.in scholarship 2026 Rajasthan students",
            "site:gov.in scholarship 2026 Maharashtra students",
            "site:gov.in scholarship 2026 Karnataka students",
            "site:gov.in scholarship 2026 Tamil Nadu students",
            "site:gov.in scholarship 2026 Telangana students",
            "site:gov.in scholarship 2026 Andhra Pradesh students",
            "site:gov.in scholarship 2026 Kerala students",
            "site:gov.in scholarship 2026 West Bengal students",
            "site:gov.in scholarship 2026 Gujarat students",
            "site:gov.in scholarship 2026 Bihar students",
            "site:gov.in scholarship 2026 Jharkhand students",
            "site:gov.in scholarship 2026 Odisha students",
            "site:gov.in scholarship 2026 Assam students",
            "site:gov.in scholarship 2026 Chhattisgarh students",
            "site:gov.in scholarship 2026 Madhya Pradesh students",
            "site:gov.in scholarship 2026 Uttarakhand students",
            "site:gov.in scholarship 2026 Himachal Pradesh students",

            # State portals
            "scholarship.up.gov.in 2026 scholarship",
            "scholarship.up.gov.in post matric scholarship 2026",
            "ssp.postmatric.karnataka.gov.in scholarship 2026",
            "Karnataka post matric scholarship 2026",
            "haryanascbc.gov.in scholarship 2026",
            "Haryana scholarship 2026 students",
            "scholarships.punjab.gov.in 2026",
            "Punjab scholarship 2026 college students",
            "mahadbt.maharashtra.gov.in scholarship 2026",
            "Maharashtra scholarship 2026 students",
            "scholarships.gov.in Maharashtra scholarship 2026",

            # ============================================================
            # ADDITIONAL STATE SCHOLARSHIPS (31-60)
            # ============================================================
            "site:gov.in scholarship 2026 Jammu Kashmir students",
            "site:gov.in scholarship 2026 Sikkim students",
            "site:gov.in scholarship 2026 Goa students",
            "site:gov.in scholarship 2026 Tripura students",
            "site:gov.in scholarship 2026 Manipur students",
            "site:gov.in scholarship 2026 Meghalaya students",
            "site:gov.in scholarship 2026 Mizoram students",
            "site:gov.in scholarship 2026 Nagaland students",
            "site:gov.in scholarship 2026 Arunachal Pradesh students",
            "site:gov.in scholarship 2026 Puducherry students",
            "site:gov.in scholarship 2026 Chandigarh students",
            "site:gov.in scholarship 2026 Ladakh students",
            "site:digitalgujarat.gov.in scholarship 2026 application",
            "site:scholarship.odisha.gov.in state scholarship 2026",
            "site:egrantz.kerala.gov.in post matric scholarship 2026",
            "site:oasis.gov.in west bengal scholarship 2026",
            "site:wbmdfcscholarship.org west bengal minority 2026",
            "site:harchhatrabritti.highereduhry.ac.in haryana 2026",
            "site:sje.rajasthan.gov.in scholarship apply online 2026",
            "site:scholarships.wbtada.gov.in tribal scholarship 2026",
            "site:prerna.up.gov.in scholarship status 2026",
            "site:ekalyan.cgg.gov.in jharkhand scholarship 2026",
            "site:ekalyan.bih.nic.in bihar scholarship status 2026",
            "site:medhasoft.bih.nic.in bihar post matric 2026",
            "site:bsp.ap.gov.in andhra pradesh scholarship 2026",
            "site:telangana.gov.in epass scholarship status 2026",
            "site:ssp.goa.gov.in state scholarship portal 2026",
            "site:e-district.delhigovt.nic.in delhi scholarship 2026",
            "site:mpascholarship.gov.in madhya pradesh 2026",
            "site:scholarship.uttarakhand.gov.in state portal 2026",
        ],
        source_types=["GOVERNMENT", "STATE"],
    ),

    DiscoveryStrategy(
        name="university_scholarships",
        queries=[
            # ============================================================
            # UNIVERSITY / INSTITUTES (Original)
            # ============================================================
            "site:ac.in scholarship 2026 apply online",
            "site:ac.in scholarships 2026 undergraduate students",
            "site:ac.in scholarship 2026 BTech students",
            "site:ac.in scholarship 2026 merit based",
            "site:ac.in scholarship 2026 need based",
            "site:ac.in scholarship 2026 financial aid",
            "site:ac.in scholarship 2026 tuition fee waiver",
            "site:ac.in scholarship 2026 admission scholarship",
            "site:ac.in scholarship 2026 last date",
            "site:ac.in scholarship 2026 international students India",
            "site:edu.in scholarship 2026 students apply",
            "site:edu.in scholarship 2026 merit scholarship",
            "site:edu.in scholarship 2026 undergraduate",
            "university scholarship India 2026 BTech merit",
            "college scholarship India 2026 engineering students",
            
            # UGC
            "site:ugc.gov.in scholarship 2026",
            "site:ugc.gov.in scholarships 2026 students",
            "site:ugc.gov.in scholarship scheme 2026",
            "site:ugc.gov.in fellowship scholarship 2026",
            "UGC scholarship 2026 undergraduate",
            "UGC scholarship 2026 college students",
            "UGC scholarship 2026 university students",

            # ============================================================
            # ADDITIONAL UNIVERSITY/ACADEMIC QUERIES (61-90)
            # ============================================================
            "site:iitb.ac.in scholarship 2026 undergraduate BTech",
            "site:iitd.ac.in scholarship merit cum means 2026",
            "site:iitm.ac.in financial assistance students 2026",
            "site:iitkgp.ac.in scholarship 2026 online application",
            "site:iitk.ac.in scholarship prize merit 2026",
            "site:iisc.ac.in research fellowship phd 2026",
            "site:bits-pilani.ac.in scholarship fee waiver 2026",
            "site:du.ac.in scholarship 2026 undergraduate college",
            "site:bhu.ac.in scholarship student support 2026",
            "site:amu.ac.in student scholarship financial aid 2026",
            "site:jnu.ac.in fellowship fellowship program 2026",
            "site:annauniv.edu scholarship 2026 college students",
            "site:vtu.ac.in scholarship 2026 engineering college",
            "site:jntuh.ac.in scholarship 2026 engineering BTech",
            "site:aktu.ac.in scholarship up government 2026",
            "site:nitrkl.ac.in scholarship merit means BTech 2026",
            "site:nitt.edu scholarship financial assistance 2026",
            "site:bits-hyderabad.ac.in scholarship fee concession 2026",
            "site:vit.ac.in scholarship support fee waiver 2026",
            "site:srmist.edu.in scholarship founder merit 2026",
            "site:manipal.edu scholarship financial aid 2026",
            "site:amrita.edu scholarship undergraduate merit 2026",
            "site:thapar.edu scholarship entry merit 2026",
            "site:pec.ac.in scholarship engineering students 2026",
            "site:dseu.ac.in scholarship delhi students 2026",
            "IIT scholarship merit cum means 2026 BTech",
            "NIT scholarship financial assistance 2026 engineering",
            "PMRF fellowship application process 2026",
            "PMRF research fellowship guidelines 2026-27",
            "Prime Minister Research Fellowship 2026 status",
        ],
        source_types=["UNIVERSITY"],
    ),

    DiscoveryStrategy(
        name="corporate_csr_scholarships",
        queries=[
            # ============================================================
            # PRIVATE / CSR (Original)
            # ============================================================
            "CSR scholarship 2026 India apply online",
            "CSR scholarships 2026 Indian students",
            "corporate scholarship 2026 India students",
            "private scholarship 2026 India students",
            "company scholarship 2026 India",
            "scholarship 2026 India engineering students",
            "scholarship 2026 India BTech students",
            "scholarship 2026 computer science students India",
            "scholarship 2026 undergraduate engineering India",
            "scholarship 2026 college students India",

            # Major corporate providers
            "Reliance Foundation scholarship 2026",
            "Tata scholarship 2026 India students",
            "Aditya Birla scholarship 2026",
            "HDFC scholarship 2026 students",
            "Kotak scholarship 2026 India",
            "SBI scholarship 2026 India",
            "LIC scholarship 2026 students",
            "ONGC scholarship 2026 students",
            "Mahindra scholarship 2026 students",
            "Infosys scholarship 2026 students",
            "Google scholarship 2026 India students",
            "Microsoft scholarship 2026 India students",
            "Amazon scholarship 2026 India students",
            "Flipkart scholarship 2026 India students",
            "Coca Cola scholarship 2026 India students",

            # ============================================================
            # ADDITIONAL CORPORATE CSR QUERIES (91-125)
            # ============================================================
            "Wipro Cares scholarship 2026 application",
            "Infosys Foundation scholarship 2026 girls",
            "L&T Build India scholarship 2026 engineering",
            "HCL Foundation scholarship 2026 college",
            "Adani Foundation Gyan Jyoti scholarship 2026",
            "Jindal Star scholarship 2026 apply online",
            "GMR Varalakshmi Foundation scholarship 2026",
            "DLF Foundation scholarship 25-26 college",
            "Adobe India Women in Technology scholarship 2026",
            "L'Oreal India For Young Women in Science scholarship 2026",
            "Samsung Star Scholar program 2026 IIT NIT",
            "Sony India scholarship 2026 computer science",
            "Intel India scholarship 2026 women engineering",
            "HP India student scholarship 2026 apply",
            "Dell Technologies scholarship 2026 students",
            "Lenovo India student education scholarship 2026",
            "Maruti Suzuki CSR scholarship 2026 college",
            "Hyundai Hope Foundation scholarship 2026",
            "Toyota India student scholarship scheme 2026",
            "Honda DCT scholarship 2026 engineering",
            "JSW Foundation scholarship 2026 merit means",
            "Muthoot M George scholarship 2025-2026",
            "Federal Bank Local Help scholarship 2026",
            "South Indian Bank student scholarship 2026",
            "Axis Bank CSR education scholarship 2026",
            "ICICI Foundation scholarship 2026 college",
            "Cognizant Foundation scholarship 2026 BTech",
            "Capgemini CSR scholarship 2026 women engineering",
            "TCS Foundation scholarship 2026 coding students",
            "Tech Mahindra Foundation scholarship 2026",
            "Oracle India student scholarship 2026 cs",
            "Cisco India women in tech scholarship 2026",
            "Qualcomm India research fellowship engineering 2026",
            "Nvidia India research fellowship PhD 2026",
            "AMD India student scholarship BTech 2026",
        ],
        source_types=["CORPORATE"],
    ),

    DiscoveryStrategy(
        name="foundation_scholarships",
        queries=[
            # ============================================================
            # FOUNDATION / NGO (Original)
            # ============================================================
            "site:org scholarship 2026 Indian students apply",
            "site:org.in scholarship 2026 students India",
            "foundation scholarship 2026 India apply online",
            "trust scholarship 2026 India students",
            "NGO scholarship 2026 India students",
            "foundation scholarship 2026 undergraduate India",
            "foundation scholarship 2026 engineering students India",
            "trust scholarship 2026 college students India",
            "NGO scholarship 2026 college students India",
            "charitable trust scholarship 2026 India",
            "education foundation scholarship 2026 India",
            "merit scholarship foundation 2026 India",
            "need based scholarship foundation 2026 India",
            "scholarship for economically weaker students 2026 foundation",
            "scholarship for engineering students 2026 foundation India",

            # ============================================================
            # ADDITIONAL FOUNDATION/NGO QUERIES (126-155)
            # ============================================================
            "Aga Khan Foundation scholarship 2026-2027",
            "Narotam Sekhsaria Foundation scholarship 2026 pg",
            "KC Mahindra Education Trust scholarship 2026 pg",
            "Inlaks Shivdasani Foundation scholarship 2026 study abroad",
            "Sitaram Jindal Foundation scholarship scheme 2026",
            "Azim Premji Foundation teacher children scholarship 2026",
            "Shiv Nadar Foundation scholarship 2026 university",
            "Fair and Lovely Foundation scholarship women 2026",
            "Lalaji Memorial Foundation scholarship 2026",
            "OP Jindal Engineering Management scholarship OPJEMS 2026",
            "Inlaks Fellowship program application guidelines 2026",
            "Aga Khan International scholarship program 2026 India",
            "Rotary Foundation scholarship 2026 higher education",
            "Lions Club International scholarship 2026 students",
            "Smile Foundation education support scholarship 2026",
            "Cry India student education scholarship 2026",
            "Helpage India scholarship scheme 2026",
            "British Council Great scholarships India 2026",
            "Fulbright Nehru Master fellowships application 2026",
            "USIEF Fulbright fellowship programs India 2026",
            "Shastri Indo-Canadian Institute fellowship 2026",
            "Dawoodi Bohra Trust education scholarship 2026",
            "Jain Education Trust scholarship 2026 online",
            "Sikh Human Development Foundation SHDF scholarship 2026",
            "Edhi Foundation student scholarship program 2026",
            "Ford Foundation Fellowship program India 2026",
            "Bill and Melinda Gates scholarship India 2026",
            "MacArthur Foundation fellowship 2026 research",
            "Sir Ratan Tata Trust scholarship application 2026",
            "J N Tata Endowment loan scholarship 2026-27",
        ],
        source_types=["FOUNDATION", "TRUST", "NGO"],
    ),

    DiscoveryStrategy(
        name="eligibility_specific",
        queries=[
            # ============================================================
            # ELIGIBILITY / CATEGORY (Original)
            # ============================================================
            "scholarship 2026 India BTech computer science students",
            "scholarship 2026 India CSE students",
            "scholarship 2026 India undergraduate students merit",
            "scholarship 2026 India family income below 5 lakh",
            "scholarship 2026 India family income below 3 lakh",
            "scholarship 2026 India students CGPA 8",
            "scholarship 2026 India students 80 percent marks",
            "scholarship 2026 India first year college students",
            "scholarship 2026 India female engineering students",
            "scholarship 2026 India students from rural areas",
            
            # Category specific
            "scholarship 2026 girl students India",
            "scholarship 2026 women students India",
            "scholarship 2026 economically weaker students India",
            "scholarship 2026 disabled students India",
            "scholarship 2026 SC students India",
            "scholarship 2026 ST students India",
            "scholarship 2026 OBC students India",
            "scholarship 2026 minority students India",
            "scholarship 2026 rural students India",
            "scholarship 2026 first generation college students India",

            # Academic Level
            "undergraduate scholarship 2026 India",
            "BTech scholarship 2026 India",
            "BE scholarship 2026 India",
            "engineering scholarship 2026 India",
            "computer science scholarship 2026 India",
            "technical degree scholarship 2026 India",
            "professional degree scholarship 2026 India",
            "college scholarship 2026 India",
            "university scholarship 2026 India",
            "postgraduate scholarship 2026 India",
            "masters scholarship 2026 India",

            # ============================================================
            # ADDITIONAL ELIGIBILITY & DISCIPLINE QUERIES (156-190)
            # ============================================================
            "scholarship 25-26 single parent child India",
            "scholarship 2026 orphan students education India",
            "scholarship 2026 war widows children education India",
            "scholarship 2026 wards of police personnel India",
            "scholarship 2026 single girl child PG UGC",
            "fellowship 2026 doctoral women post doc India",
            "scholarship 2026 MBBS students medical India",
            "scholarship 2026 BDS dental students India",
            "scholarship 2026 Pharmacy GPAT qualified students",
            "scholarship 2026 Nursing nursing college India",
            "scholarship 2026 Law students LLB CLAT India",
            "scholarship 2026 MBA students management India",
            "scholarship 2026 MCA computer application India",
            "scholarship 2026 CA CS CMA articleship stipend",
            "scholarship 2026 Agriculture BSc agriculture students",
            "scholarship 2026 Architecture BArch students NATA",
            "scholarship 2026 design BDes NID NIFT India",
            "scholarship 2026 pilot training commercial aviation",
            "scholarship 2026 physical disability orthopedically",
            "scholarship 2026 visually impaired blind students",
            "scholarship 2026 hearing impaired deaf students",
            "scholarship 2026 learning disability special needs",
            "scholarship 2026 transgender students higher education",
            "scholarship 2026 sports national level players SAI",
            "scholarship 2026 state level sports achievements",
            "scholarship 2026 merit means CGPA 9 colleges",
            "scholarship 2026 family income less than 1 lakh",
            "scholarship 2026 first year BTech CSE NITs",
            "scholarship 2026 second year lateral entry diploma",
            "scholarship 2026 final year project grant engineering",
            "fellowship 2026 post graduate research fellowship",
            "scholarship 2026 non collegiate women education",
            "scholarship 2026 distance education IGNOU students",
            "scholarship 2026 vocational training ITI diploma",
            "scholarship 2026 polytechnic college students state",
        ],
        source_types=["SCHOLARSHIP"],
    ),

    DiscoveryStrategy(
        name="scholarship_portals",
        queries=[
            # ============================================================
            # PORTALS / AGGREGATORS (Original)
            # ============================================================
            "site:scholarships.gov.in scholarship 2026",
            "site:scholarships.gov.in 2026 scholarship",
            "site:scholarships.gov.in scholarship 2026 apply",
            "site:scholarships.gov.in 2026-27 scholarship",
            "site:scholarships.gov.in 2026-27 scheme",
            "site:scholarships.gov.in scholarship application 2026",
            "site:scholarships.gov.in higher education scholarship",
            "site:scholarships.gov.in college university scholarship",

            # AICTE
            "site:aicte-india.org scholarship 2026",
            "site:aicte-india.org scholarships 2026 students",
            "site:aicte-india.org scholarship scheme 2026",
            "site:aicte-india.org scholarship 2026 engineering",
            "site:aicte-india.org scholarship 2026 technical degree",
            "site:aicte-india.org scholarship 2026 diploma",
            "AICTE scholarship 2026 students",
            "AICTE scholarship schemes 2026",
            "AICTE Pragati scholarship 2026",
            "AICTE Saksham scholarship 2026",
            "AICTE Swanath scholarship 2026",

            # Aggregators
            "scholarships India 2026 apply online",
            "scholarships India 2026 undergraduate",
            "scholarships India 2026 college students",
            "scholarships India 2026 engineering students",
            "scholarships India 2026 BTech",
            "scholarships India 2026 computer science",
            "scholarships India 2026 merit based",
            "scholarships India 2026 need based",
            "scholarships India 2026 financial aid",
            "scholarships India 2026 last date",
            "scholarship portal India 2026",
            "student scholarship portal India 2026",
            "college scholarship portal India 2026",
            "engineering scholarship portal India 2026",

            # Deadlines
            "scholarship 2026 application open India",
            "scholarship 2026 applications open now India",
            "scholarship 2026 last date September India",
            "scholarship 2026 last date October India",
            "scholarship 2026 last date November India",
            "scholarship 2026 last date December India",
            "scholarship 2026 apply before deadline India",
            "scholarship 2026 currently open India",

            # ============================================================
            # ADDITIONAL PORTAL & TIMING QUERIES (191-230)
            # ============================================================
            "site:buddy4study.com scholarship open 2026",
            "site:buddy4study.com active application 2026",
            "site:buddy4study.com engineering scholarships 2026",
            "site:vidyasaarathi.co.in active schemes 2026",
            "site:vidyasaarathi.co.in scholarship registration 2026",
            "site:vidyasaarathi.co.in check status 2026",
            "site:vidyasauda.com active scholarships 2026",
            "site:vidyasauda.com engineering students 2026",
            "site:scholarships.gov.in central schemes status 2026",
            "site:scholarships.gov.in state schemes status 2026",
            "site:scholarships.gov.in ugc schemes application 2026",
            "site:scholarships.gov.in aicte schemes registration 2026",
            "site:scholarships.gov.in renewal guide 2026-27",
            "site:scholarships.gov.in check eligibility 2026",
            "scholarship last date extended India 2026",
            "scholarship registration start date 2026 India",
            "scholarship application deadline extended 2026",
            "scholarship portal open date 2026-27 India",
            "central sector scholarship scheme 2026 application status",
            "post matric scholarship portal open 2026 state",
            "pre matric scholarship portal active date 2026",
            "national fellowship portal application form 2026",
            "minority scholarship online application portal 2026",
            "disabled students scholarship registration link 2026",
            "merit cum means scholarship last date to apply 2026",
            "vidya samunnathi scholarship application open 2026",
            "vidyadhan scholarship scheme application open 2026",
            "care rating scholarship registration portal 2026",
            "sitaram jindal scholarship online apply date 2026",
            "kotak kanya scholarship active application link 2026",
            "mahindra finance scholarship portal active 2026",
            "keep india smiling scholarship online application 2026",
            "hdfc badhte kadam scholarship online application 2026",
            "lic golden jubilee scholarship online application 2026",
            "sbi hope scholarship portal active registration 2026",
            "ongc scholarship registration portal open 2026",
            "reliance foundation pg scholarship application portal 2026",
            "reliance foundation ug scholarship registration portal 2026",
            "tata trust scholarship registration link 2026",
            "aditya birla scholarship application guidelines 2026",
        ],
        source_types=["SCHOLARSHIP_PORTAL"],
    )
]
