CREATE TABLE crawl_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    discovery_candidate_id BIGINT,

    start_url TEXT NOT NULL,

    max_depth INTEGER,
    max_pages INTEGER,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,

    status TEXT NOT NULL DEFAULT 'RUNNING'
        CHECK (
            status IN (
                'RUNNING',
                'COMPLETED',
                'FAILED'
            )
        ),

    total_pages_visited INTEGER NOT NULL DEFAULT 0,
    total_pages_failed INTEGER NOT NULL DEFAULT 0,
    total_scholarships_extracted INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_crawl_discovery_candidate
        FOREIGN KEY (discovery_candidate_id)
        REFERENCES discovery_candidates(id)
        ON DELETE SET NULL
);


-- ============================================================
-- CRAWL RUN INDEXES
-- ============================================================

CREATE INDEX idx_crawl_runs_candidate
    ON crawl_runs(discovery_candidate_id);

CREATE INDEX idx_crawl_runs_status
    ON crawl_runs(status);


-- ============================================================
-- 4. CRAWL PAGES
-- One row = one page encountered during crawling
-- ============================================================

CREATE TABLE crawl_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    crawl_run_id BIGINT NOT NULL,

    parent_page_id BIGINT,

    url TEXT NOT NULL,
    final_url TEXT,

    depth INTEGER NOT NULL DEFAULT 0,

    title TEXT,
    status_code INTEGER,

    page_type TEXT
        CHECK (
            page_type IN (
                'NORMAL_PAGE',
                'PORTAL_PAGE',
                'SCHOLARSHIP_LISTING',
                'SCHOLARSHIP_DETAIL'
            )
        ),

    crawl_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (
            crawl_status IN (
                'PENDING',
                'CRAWLED',
                'FAILED',
                'SKIPPED'
            )
        ),

    crawl_action TEXT
        CHECK (
            crawl_action IN (
                'EXTRACT_SCHOLARSHIPS',
                'FOLLOW_LINKS',
                'STOP_MAX_DEPTH',
                'SKIP',
                'FAILED'
            )
        ),

    skip_reason TEXT,

    links_found INTEGER NOT NULL DEFAULT 0,
    links_queued INTEGER NOT NULL DEFAULT 0,
    scholarships_extracted INTEGER NOT NULL DEFAULT 0,

    extraction_method TEXT
        CHECK (
            extraction_method IN (
                'DETERMINISTIC',
                'LLM',
                'NONE'
            )
        ),

    -- Useful for debugging the crawler.
    decision_metadata JSONB,

    error_message TEXT,

    crawled_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_crawl_page_run
        FOREIGN KEY (crawl_run_id)
        REFERENCES crawl_runs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_crawl_page_parent
        FOREIGN KEY (parent_page_id)
        REFERENCES crawl_pages(id)
        ON DELETE SET NULL
);


-- ============================================================
-- CRAWL PAGE INDEXES
-- ============================================================

CREATE INDEX idx_crawl_pages_run
    ON crawl_pages(crawl_run_id);

CREATE INDEX idx_crawl_pages_parent
    ON crawl_pages(parent_page_id);

CREATE INDEX idx_crawl_pages_url
    ON crawl_pages(url);

CREATE INDEX idx_crawl_pages_page_type
    ON crawl_pages(page_type);

CREATE INDEX idx_crawl_pages_status
    ON crawl_pages(crawl_status);