-- ============================================================
-- 1. DISCOVERY RUNS
-- One row = one complete Discovery execution
-- ============================================================

CREATE TABLE discovery_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,

    status TEXT NOT NULL DEFAULT 'RUNNING'
        CHECK (
            status IN (
                'RUNNING',
                'COMPLETED',
                'FAILED'
            )
        ),

    total_queries INTEGER NOT NULL DEFAULT 0,
    total_results INTEGER NOT NULL DEFAULT 0,
    total_candidates INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 2. DISCOVERY CANDIDATES
-- One row = one candidate URL discovered from web search
-- ============================================================

CREATE TABLE discovery_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    discovery_run_id BIGINT NOT NULL,

    title TEXT NOT NULL,
    url TEXT NOT NULL,
    domain TEXT NOT NULL,

    snippet TEXT,

    discovery_strategy TEXT,
    discovery_query TEXT,
    discovered_from TEXT,

    source_type TEXT,
    candidate_type TEXT,

    -- NULL during discovery.
    -- Validator/classifier can determine this later.
    is_official_source BOOLEAN,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_discovery_run
        FOREIGN KEY (discovery_run_id)
        REFERENCES discovery_runs(id)
        ON DELETE CASCADE
);


-- ============================================================
-- DISCOVERY INDEXES
-- ============================================================

CREATE INDEX idx_discovery_candidates_run
    ON discovery_candidates(discovery_run_id);

CREATE INDEX idx_discovery_candidates_domain
    ON discovery_candidates(domain);

CREATE INDEX idx_discovery_candidates_candidate_type
    ON discovery_candidates(candidate_type);

CREATE INDEX idx_discovery_candidates_source_type
    ON discovery_candidates(source_type);