-- ============================================================
-- MIGRATION: recheck_runs
--
-- One row per RecheckService.run() call (monitoring/recheck_scholarships.py),
-- i.e. one row per time a recheck BATCH actually finished processing -
-- not one row per cron tick.
--
-- WHY NOT just read cron.job_run_details for "last updated"?
-- pg_net dispatches the HTTP call to api/main.py asynchronously - the
-- cron job's SQL statement "finishes" the instant the request is
-- QUEUED, not when the recheck actually completes. This table is
-- written by the application itself, after the work is genuinely
-- done, so `completed_at` here is trustworthy for a dashboard.
--
-- Mirrors the same started_at/completed_at/status shape as
-- crawl_runs / discovery_runs (see crawler_node.sql / discovery_node.sql).
--
-- Run this AFTER recheck_migration.sql (scholarship_monitoring /
-- scholarship_changes must already exist).
-- ============================================================

CREATE TABLE IF NOT EXISTS recheck_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,

    status TEXT NOT NULL DEFAULT 'RUNNING'
        CHECK (
            status IN (
                'RUNNING',
                'COMPLETED',
                'FAILED'
            )
        ),

    -- Parameters the run was invoked with.
    batch_size INTEGER,
    stale_after_hours INTEGER,
    include_inactive BOOLEAN NOT NULL DEFAULT FALSE,

    -- Results (mirrors RecheckService.run()'s summary dict).
    total_checked INTEGER NOT NULL DEFAULT 0,
    total_still_active INTEGER NOT NULL DEFAULT 0,
    total_reactivated INTEGER NOT NULL DEFAULT 0,
    total_marked_inactive INTEGER NOT NULL DEFAULT 0,
    total_fetch_failed INTEGER NOT NULL DEFAULT 0,
    total_fields_updated INTEGER NOT NULL DEFAULT 0,
    total_errors INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recheck_runs_completed_at
    ON recheck_runs(completed_at DESC);

CREATE INDEX IF NOT EXISTS idx_recheck_runs_status
    ON recheck_runs(status);


-- ============================================================
-- CONVENIENCE VIEW: latest completed run
--
-- select * from latest_recheck_run;
--
-- Dashboard can query this view directly, or hit the API's
-- GET /recheck/last-run (api/main.py), which reads the same data via
-- SupabaseStore.get_last_recheck_run().
-- ============================================================

CREATE OR REPLACE VIEW latest_recheck_run AS
SELECT *
FROM recheck_runs
WHERE status = 'COMPLETED'
ORDER BY completed_at DESC
LIMIT 1;