-- ============================================================
-- MIGRATION: scholarship_monitoring (separate table, trigger-synced)
--
-- Rather than bolting recheck-tracking columns directly onto
-- `scholarships`, this keeps monitoring state (is it still live? when
-- was it last checked? how many times has checking it failed in a
-- row?) in its own 1:1-linked table. `scholarships` still gets an
-- is_active column so any consumer that just queries `scholarships`
-- directly (without a join) still sees the right thing - a trigger
-- keeps the two in sync automatically, so application code never has
-- to remember to write to both places.
-- ============================================================

ALTER TABLE scholarships
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_scholarships_is_active
    ON scholarships(is_active);


CREATE TABLE IF NOT EXISTS scholarship_monitoring (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    scholarship_id BIGINT NOT NULL UNIQUE,

    last_checked_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_monitoring_scholarship
        FOREIGN KEY (scholarship_id)
        REFERENCES scholarships(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_monitoring_last_checked
    ON scholarship_monitoring(last_checked_at);

CREATE INDEX IF NOT EXISTS idx_monitoring_is_active
    ON scholarship_monitoring(is_active);


-- ============================================================
-- TRIGGER 1: auto-create a monitoring row whenever a scholarship
-- is inserted, so the recheck job never has to special-case
-- "scholarship exists but has no monitoring row yet".
-- ============================================================

CREATE OR REPLACE FUNCTION create_scholarship_monitoring_row()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO scholarship_monitoring (scholarship_id)
    VALUES (NEW.id)
    ON CONFLICT (scholarship_id) DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_create_monitoring_row ON scholarships;

CREATE TRIGGER trg_create_monitoring_row
    AFTER INSERT ON scholarships
    FOR EACH ROW
    EXECUTE FUNCTION create_scholarship_monitoring_row();


-- ============================================================
-- TRIGGER 2: propagate is_active changes from scholarship_monitoring
-- back onto scholarships.is_active, so `scholarships` alone stays
-- accurate for consumers that don't join against monitoring.
-- ============================================================

CREATE OR REPLACE FUNCTION sync_scholarship_active_status()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_active IS DISTINCT FROM OLD.is_active THEN
        UPDATE scholarships
        SET is_active = NEW.is_active,
            updated_at = NOW()
        WHERE id = NEW.scholarship_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_active_status ON scholarship_monitoring;

CREATE TRIGGER trg_sync_active_status
    AFTER UPDATE ON scholarship_monitoring
    FOR EACH ROW
    EXECUTE FUNCTION sync_scholarship_active_status();


-- ============================================================
-- BACKFILL: create monitoring rows for scholarships that already
-- existed before this migration ran.
-- ============================================================

INSERT INTO scholarship_monitoring (scholarship_id)
SELECT id FROM scholarships
ON CONFLICT (scholarship_id) DO NOTHING;


-- ============================================================
-- SCHOLARSHIP CHANGES (unchanged from the earlier migration - audit
-- trail of field-level changes detected on recheck)
-- ============================================================

CREATE TABLE IF NOT EXISTS scholarship_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    scholarship_id BIGINT NOT NULL,

    field_name TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,

    change_type TEXT NOT NULL DEFAULT 'FIELD_UPDATED'
        CHECK (
            change_type IN (
                'FIELD_UPDATED',
                'MARKED_INACTIVE',
                'REACTIVATED'
            )
        ),

    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_change_scholarship
        FOREIGN KEY (scholarship_id)
        REFERENCES scholarships(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_scholarship_changes_scholarship
    ON scholarship_changes(scholarship_id);

CREATE INDEX IF NOT EXISTS idx_scholarship_changes_detected_at
    ON scholarship_changes(detected_at);