CREATE TABLE scholarships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    crawl_run_id BIGINT,

    crawl_page_id BIGINT,

    title TEXT NOT NULL,

    organization TEXT,

    scheme_type TEXT
        CHECK (
            scheme_type IN (
                'MERIT_BASED',
                'WELFARE_BASED'
            )
        ),

    application_start DATE,
    application_end DATE,

    source_url TEXT NOT NULL,

    guidelines_url TEXT,
    faq_url TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_scholarship_crawl_run
        FOREIGN KEY (crawl_run_id)
        REFERENCES crawl_runs(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_scholarship_crawl_page
        FOREIGN KEY (crawl_page_id)
        REFERENCES crawl_pages(id)
        ON DELETE SET NULL
);


-- ============================================================
-- SCHOLARSHIP INDEXES
-- ============================================================

CREATE INDEX idx_scholarships_crawl_run
    ON scholarships(crawl_run_id);

CREATE INDEX idx_scholarships_crawl_page
    ON scholarships(crawl_page_id);

CREATE INDEX idx_scholarships_title
    ON scholarships(title);

CREATE INDEX idx_scholarships_source_url
    ON scholarships(source_url);


-- ============================================================
-- 6. SCHOLARSHIP VALIDATIONS
-- One row = one validation execution/result
-- ============================================================

CREATE TABLE scholarship_validations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    scholarship_id BIGINT NOT NULL,

    status TEXT NOT NULL
        CHECK (
            status IN (
                'VERIFIED',
                'HIGH_CONFIDENCE',
                'LIKELY_VALID',
                'NEEDS_REVIEW',
                'LOW_CONFIDENCE'
            )
        ),

    legitimacy_score INTEGER NOT NULL
        CHECK (
            legitimacy_score >= 0
            AND legitimacy_score <= 100
        ),

    confidence NUMERIC(4,3)
        CHECK (
            confidence >= 0
            AND confidence <= 1
        ),

    verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Stores the individual validator checks:
    -- title_present
    -- source_domain
    -- source_reachable
    -- guidelines_reachable
    -- faq_reachable
    -- scholarship_title_signal
    -- application_dates
    verification_checks JSONB NOT NULL DEFAULT '[]'::JSONB,

    -- Stores validator warnings.
    warnings JSONB NOT NULL DEFAULT '[]'::JSONB,

    -- Optional snapshot of source/domain information
    -- used during validation.
    source_snapshot JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_validation_scholarship
        FOREIGN KEY (scholarship_id)
        REFERENCES scholarships(id)
        ON DELETE CASCADE
);


-- ============================================================
-- VALIDATION INDEXES
-- ============================================================

CREATE INDEX idx_scholarship_validations_scholarship
    ON scholarship_validations(scholarship_id);

CREATE INDEX idx_scholarship_validations_status
    ON scholarship_validations(status);

CREATE INDEX idx_scholarship_validations_score
    ON scholarship_validations(legitimacy_score);